# configure windows firewall for Caboodle per Epic specs
# note 1 - redundant IF we always disable the firewall service
# note 2 - does not address NSG
# note 3 - DAC port rule is redundant microsoft_sql role, "Firewall rule to allow SQL on TCP port 1433 and 1434"

---
- name: Add tags to all tasks
  tags:
    - os
    - firewall
    - caboodle
  block:
    - name: Check whether this is a Caboodle VM. If not, skip the rest of this task
      set_fact:
        isCaboodle: true
      loop: "{{ sql_dbs }}"
      when: item.name is search("caboodle", ignorecase=True)
    - name: DAC Port
      community.windows.win_firewall_rule:
        action: allow
        direction: in
        enabled: true
        name: SQL DAC Inbound allow
        localip: any
        localport: 1434
        protocol: tcp
        remoteport: any
      when: isCaboodle is defined
    - name: Execution Service
      community.windows.win_firewall_rule:
        action: allow
        direction: in
        enabled: true
        name: Warehouse Execution Service Inbound Allow
        localip: any
        localport: 29987-30987
        protocol: tcp
        remoteport: any
      when: isCaboodle is defined
    - name: Enable DTC firewall rule
      community.windows.win_firewall_rule:
        enabled: true
        group: Distributed Transaction Coordinator
      when: isCaboodle is defined
    - name: Set DTC network and security configuration
      ansible.windows.win_powershell:
        script: |
          Set-DtcNetworkSetting -DtcName "Local" -InboundTransactionsEnabled 1 -OutboundTransactionsEnabled 1 -RemoteClientAccessEnabled 1 -LUTransactionsEnabled 1 -AuthenticationLevel "Mutual" -Confirm:$False
      when: isCaboodle is defined