# does not include .NET, which is included with OS. If needed, it can be added in the microsoft_sql role, which already adds server features.
---
- name: TCP Registry Settings
  ansible.builtin.include_tasks:
    file: tcpregistry.yml
  tags:
    - os
    - registry
    - tcp
    - clarity
    - caboodle
- name: Open Caboodle Firewall
  ansible.builtin.include_tasks:
    file: firewallcaboodle.yml
  tags:
    - os
    - firewall
    - caboodle
- name: Set High Performance Power Plan
  ansible.builtin.include_tasks:
    file: hpp.yml
  tags:
    - os
    - caboodle
    - clarity
- name: Verify Kernel-only dump
  ansible.builtin.include_tasks:
    file: verifykerneldump.yml
  tags:
    - os
    - caboodle
    - clarity
- name: Disable Memory Pressure Protection
  ansible.builtin.include_tasks:
    file: disablempp.yml
  tags:
    - os
    - caboodle
    - clarity
- name: Grant User privileges
  ansible.builtin.include_tasks:
    file: cogitousersos.yml
  tags:
    - os
    - caboodle
    - clarity
- name: Create SourceFiles directory
  ansible.builtin.include_tasks:
    file: sourcefiles_directory.yml
  tags:
    - os
    - caboodle
- name: Grant permissions on SQL install folder to engine service account
  ansible.builtin.include_tasks:
    file: sqlfolderpermissions.yml
  tags:
    - SQL
    - OS
    - Caboodle
    - Clarity
- name: Apply Epic's best practice SQL configurations
  ansible.builtin.include_tasks:
    file: sqltuneforepic.yml
  tags:
    - SQL
    - OS
    - Caboodle
    - Clarity
- name: Create mnt folders for sql db files
  ansible.builtin.include_tasks:
    file: mntdirectories.yml
  tags:
    - SQL
    - OS
    - Caboodle
    - Clarity
- name: Create Epic SQL Databases
  ansible.builtin.include_tasks:
    file: cogitodbcreation.yml
  tags:
    - SQL
    - OS
    - Caboodle
    - Clarity
    - database
