---
- name: TCP Registry Settings
  ansible.builtin.include_tasks:
    file: tcpregistry.yml
  tags:
    - os
    - registry
    - tcp
    - clarity
    - caboodle
- name: Open Caboodle Firewall
  ansible.builtin.include_tasks:
    file: firewallcaboodle.yml
  tags:
    - os
    - firewall
    - caboodle
