# does not include NETfeatures
---
- name: TCP Registry Settings
  ansible.builtin.include_tasks:
    file: tcpregistry.yml
  tags:
    - os
    - registry
    - tcp
    - clarity
    - caboodle
- name: Open Caboodle Firewall
  ansible.builtin.include_tasks:
    file: firewallcaboodle.yml
  tags:
    - os
    - firewall
    - caboodle
- name: Set High Performance Power Plan
  ansible.builtin.include_tasks:
    file: hpp.yml
  tags:
    - os
    - caboodle
    - clarity
- name: Verify Kernel-only dump
  ansible.builtin.include_tasks:
    file: verifykerneldump.yml
  tags:
    - os
    - caboodle
    - clarity
- name: Disable Memory Pressure Protection
  ansible.builtin.include_tasks:
    file: disablempp.yml
  tags:
    - os
    - caboodle
    - clarity
