---
- name: Add tags to all tasks
  tags:
    - sql
    - caboodle
    - clarity
    - database
    - slicerdicer
    - mnt
  block:
      - name: Expand data file paths and counts into a list
        ansible.builtin.set_fact:
          sql_dbs_expanded: "{{ sql_dbs_expanded | default([]) + [ {'name': item.data_path, 'data_files': range(1, item.data_file_count | int + 1) | list } ] }}"
        loop: "{{ sql_dbs }}"

      - name: Create SQL DB mount paths
        when: sql_dbs is defined
        ansible.windows.win_file:
          path: "{{ item.0.name }}{{ item.1 }}\\mnt"
          state: directory
        loop: "{{ sql_dbs_expanded | subelements('data_files') }}"

      - name: Grant permissions on DB mount paths
        when: sql_dbs is defined
        ansible.windows.win_owner:
          path: "{{ item.0.name }}{{ item.1 }}\\mnt"
          user: "{{ user_sqlengine }}"
        loop: "{{ sql_dbs_expanded | subelements('data_files') }}"

      - name: Create SQL log mount paths
        when: sql_dbs is defined
        ansible.windows.win_file:
          path: "{{ item.log_path }}\\mnt"
          state: directory
        loop: "{{ sql_dbs }}"

      - name: Grant permissions on log mount paths
        when: sql_dbs is defined
        ansible.windows.win_owner:
          path: "{{ item.log_path }}\\mnt"
          user: "{{ user_sqlengine }}"
        loop: "{{ sql_dbs }}"
