---
- name: Add tags to all tasks
  tags:
    - os
    - registry
    - tcp
    - clarity
    - caboodle
  block:
    - name: Open permissions on sql install folder
      ansible.windows.win_acl:
        path: S:\SQL\
        user: '{{ user_sqlengine }}'
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'None'
