---
- name: Add tags to all tasks
  tags:
    - os
    - clarity
    - caboodle
  block:
    - name: Expand SQLinstall files into a list
      ansible.builtin.set_fact:
        sql_path_users: >-
          {{ sql_path_users | default([]) +
            [{ 'path': item,
              'users': [
                user_sqlengine
              ] + dsc_sqlsysadminaccounts
            }]
          }}
      loop:
        - "{{ dsc_sqltempdbdir }}"
        - "{{ dsc_sqltempdblogdir }}"
        - "{{ dsc_installsqldatadir }}"
        - "{{ dsc_sqlbackupdir }}"
        - "{{ dsc_sqluserdbdir }}"
        - "{{ dsc_sqluserdblogdir }}"

    - name: Configure permissions on sql install folders
      ansible.windows.win_acl:
        path: '{{ item.0.path }}'
        user: '{{ item.1 }}'
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'None'
      loop: "{{ sql_path_users | subelements('users') }}"
