# Verify Kernel-only memory dump is configured
# Epic recommends 32GB initial and max size, with manual increase as needed
# look into use of override: false
---
- name: Add tags to all tasks
  tags:
    - os
    - clarity
    - caboodle
  block:
    - name: Disable automatic pagefile sizing, set initial and maximum_size
      community.windows.win_pagefile:
        drive: C
        initial_size: "{{ cogito_pagefilesize }}"
        maximum_size: "{{ cogito_pagefilesize }}"
        state: present
        automatic: false
    - name: Set Startup and Recovery settings to use Kernel-only Memory Dump
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl
        name: CrashDumpEnabled
        data: 2
        type: dword
