# Verify Kernel-only memory dump is configured
# Epic recommends 32GB initial and max size, with manual increase as needed
---
- name: Add tags to all tasks
  tags:
    - os
    - clarity
    - caboodle
  block:
    - name: Disable automatic pagefile sizing, set initial and maximum_size
      community.windows.win_pagefile:
        drive: C
        initial_size: "{{ cogito_pagefilesize }}"
        maximum_size: "{{ cogito_pagefilesize }}"
        state: present
        automatic: false
