name: Add Issues/PRs to Cloud Team Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Add to Project
        id: add-to-project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Sapphire-Health/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

      - name: Debug outputs
        run: echo "Item ID is ${{ steps.add-to-project.outputs.itemId }}"

      - name: Set Project Field (Team = Cogito)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            const projectId = "PVT_kwDOBKbEgM4A7pvO";
            const fieldId = "PVTSSF_lADOBKbEgM4A7pvOzgzxZA4";
            const optionId = "9f1e522d";
            const itemId = "${{ steps.add-to-project.outputs.itemId }}";

            console.log("Updating itemId:", itemId);

            await github.graphql(
              `mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { singleSelectOptionId: $optionId }
                  }
                ) {
                  projectV2Item { id }
                }
              }`,
              { projectId, itemId, fieldId, optionId }
            );
